export enum DEMANDE_TYPE {
  CONTESTATION = 'CONTESTATION',
  DEMANDE = 'DEMANDE',
  PROPOSITION = 'PROPOSITION',
}

export enum DEMANDE_STATUS {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}
