export enum USER_ROLE {
  SUPER_ADMIN = 'SUPER_ADMIN',
  PERMISSION_ADMIN = 'PERMISSION_ADMIN',
  CONTESTATION_ADMIN = 'CONTESTATION_ADMIN',
  DEMANDE_ADMIN = 'DEMANDE_ADMIN',
  CITIZEN = 'CITIZEN',
  ORGANIZATION = 'ORGANIZATION',
  BUSINESS='BUSINESS'
}
